services:
  - type: web
    name: airport-issue-tracker
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # This will be set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: PUBLIC_BASE_URL
        sync: false  # This will be set automatically by Render
